import json
import os
from pathlib import Path
from datetime import datetime

REPO_ROOT = Path(__file__).parent.parent
PROMOTION_RUNS_DIR = REPO_ROOT / "promotion-runs"
DASHBOARD_PATH = REPO_ROOT / "docs" / "promotion" / "STABILITY-DASHBOARD.md"

def generate_dashboard():
    """Aggregates all promotion run manifests into a stability dashboard."""
    if not PROMOTION_RUNS_DIR.exists():
        print("No promotion runs found.")
        return

    runs = []
    for run_dir in PROMOTION_RUNS_DIR.iterdir():
        if run_dir.is_dir():
            manifest_path = run_dir / "MANIFEST.json"
            if manifest_path.exists():
                try:
                    with open(manifest_path, "r", encoding="utf-8") as f:
                        runs.append(json.load(f))
                except Exception:
                    pass

    # Sort runs by timestamp descending
    runs.sort(key=lambda x: x.get("timestamp", ""), reverse=True)

    # Group by workflow_id or skill_name (if individual run)
    workflow_stats = {}
    for run in runs:
        wf_id = run.get("workflow_id", run.get("skill_name", "Unknown"))
        if wf_id not in workflow_stats:
            workflow_stats[wf_id] = {
                "total": 0,
                "pass": 0,
                "latest_status": "N/A",
                "latest_run": "N/A"
            }
        
        workflow_stats[wf_id]["total"] += 1
        status = "pass"
        for step in run.get("steps", []):
            if step.get("status") != "pass":
                status = "fail"
                break
        
        if status == "pass":
            workflow_stats[wf_id]["pass"] += 1
        
        if workflow_stats[wf_id]["latest_run"] == "N/A":
            workflow_stats[wf_id]["latest_status"] = "✅ PASS" if status == "pass" else "❌ FAIL"
            workflow_stats[wf_id]["latest_run"] = run.get("timestamp")

    # Build Markdown
    lines = [
        "# Skill Stability Dashboard",
        f"\nLast Updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n",
        "## Workflow & Skill Health Summary\n",
        "| Workflow / Skill | Latest Status | Success Rate | Total Runs | Latest Run |",
        "| :--- | :--- | :--- | :--- | :--- |"
    ]

    for wf_id, stats in workflow_stats.items():
        rate = (stats["pass"] / stats["total"]) * 100
        lines.append(f"| {wf_id} | {stats['latest_status']} | {rate:.1f}% | {stats['total']} | {stats['latest_run']} |")

    lines.append("\n## Detailed Run History\n")
    lines.append("| Timestamp | Target | Status | Run ID |")
    lines.append("| :--- | :--- | :--- | :--- |")

    for run in runs[:20]: # Show latest 20
        wf_id = run.get("workflow_id", run.get("skill_name", "Unknown"))
        status = "✅ PASS"
        for step in run.get("steps", []):
            if step.get("status") != "pass":
                status = "❌ FAIL"
                break
        lines.append(f"| {run.get('timestamp')} | {wf_id} | {status} | `{run.get('run_id')}` |")

    lines.append("\n\n---")
    lines.append(f"\nGenerated by `scripts/generate_stability_dashboard.py`.")

    DASHBOARD_PATH.parent.mkdir(parents=True, exist_ok=True)
    DASHBOARD_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Dashboard updated: {DASHBOARD_PATH}")

if __name__ == "__main__":
    generate_dashboard()
